get http://localhost:8888/.netlify/functions/hello

###
post http://localhost:8888/.netlify/functions/addtask
Content-Type: application/json

{
  "name": "this is a test task"
}

###
get http://localhost:8888/.netlify/functions/listtasks

###
delete http://localhost:8888/.netlify/functions/deletetask
Content-Type: application/json

{
  "id": "293888229792285186",
  "name": "this is a test task"
}